on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: 'ubuntu-latest',   r: 'release'}
    env:
      R_KEEP_PKG_SOURCE: yes
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setting up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Setting up R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          extra-packages: |
            any::pkgdown
            any::animation
            any::cfbfastR
            any::fastRhockey
            any::ggimage
            any::hoopR
            any::knitr
            any::mlbplotR
            any::oddsapiR
            any::pacman
            any::pak
            any::ragg
            any::remotes
            any::rsconnect
            any::sportyR
            any::tictoc
            any::wehoop
            any::zoo
            local::.
          needs: website
      - name: Install system dependencies
        run: |
          pak::pkg_install("hadley/emo")
          pak::pkg_install("r-lib/pkgapi")
        shell: Rscript {0}

      - name: Deploy package
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
